// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackend/models"
)

// BookChapterListRelationOKCode is the HTTP code returned for type BookChapterListRelationOK
const BookChapterListRelationOKCode int = 200

/*BookChapterListRelationOK 登录成功，返回登录信息

swagger:response bookChapterListRelationOK
*/
type BookChapterListRelationOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20023 `json:"body,omitempty"`
}

// NewBookChapterListRelationOK creates BookChapterListRelationOK with default headers values
func NewBookChapterListRelationOK() *BookChapterListRelationOK {
	return &BookChapterListRelationOK{}
}

// WithPayload adds the payload to the book chapter list relation o k response
func (o *BookChapterListRelationOK) WithPayload(payload *models.InlineResponse20023) *BookChapterListRelationOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book chapter list relation o k response
func (o *BookChapterListRelationOK) SetPayload(payload *models.InlineResponse20023) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookChapterListRelationOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BookChapterListRelationDefault error

swagger:response bookChapterListRelationDefault
*/
type BookChapterListRelationDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBookChapterListRelationDefault creates BookChapterListRelationDefault with default headers values
func NewBookChapterListRelationDefault(code int) *BookChapterListRelationDefault {
	if code <= 0 {
		code = 500
	}

	return &BookChapterListRelationDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the book chapter list relation default response
func (o *BookChapterListRelationDefault) WithStatusCode(code int) *BookChapterListRelationDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the book chapter list relation default response
func (o *BookChapterListRelationDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the book chapter list relation default response
func (o *BookChapterListRelationDefault) WithPayload(payload *models.Error) *BookChapterListRelationDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book chapter list relation default response
func (o *BookChapterListRelationDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookChapterListRelationDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
