// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BookChapterListRelationHandlerFunc turns a function with the right signature into a book chapter list relation handler
type BookChapterListRelationHandlerFunc func(BookChapterListRelationParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BookChapterListRelationHandlerFunc) Handle(params BookChapterListRelationParams) middleware.Responder {
	return fn(params)
}

// BookChapterListRelationHandler interface for that can handle valid book chapter list relation params
type BookChapterListRelationHandler interface {
	Handle(BookChapterListRelationParams) middleware.Responder
}

// NewBookChapterListRelation creates a new http.Handler for the book chapter list relation operation
func NewBookChapterListRelation(ctx *middleware.Context, handler BookChapterListRelationHandler) *BookChapterListRelation {
	return &BookChapterListRelation{Context: ctx, Handler: handler}
}

/*BookChapterListRelation swagger:route GET /relation/book/chapterList Relation bookChapterListRelation

获取书下章节集合

获取书的章节集合

*/
type BookChapterListRelation struct {
	Context *middleware.Context
	Handler BookChapterListRelationHandler
}

func (o *BookChapterListRelation) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBookChapterListRelationParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
