// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackend/models"
)

// RelationDefaultBookListOKCode is the HTTP code returned for type RelationDefaultBookListOK
const RelationDefaultBookListOKCode int = 200

/*RelationDefaultBookListOK 登录成功，返回登录信息

swagger:response relationDefaultBookListOK
*/
type RelationDefaultBookListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20030 `json:"body,omitempty"`
}

// NewRelationDefaultBookListOK creates RelationDefaultBookListOK with default headers values
func NewRelationDefaultBookListOK() *RelationDefaultBookListOK {
	return &RelationDefaultBookListOK{}
}

// WithPayload adds the payload to the relation default book list o k response
func (o *RelationDefaultBookListOK) WithPayload(payload *models.InlineResponse20030) *RelationDefaultBookListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation default book list o k response
func (o *RelationDefaultBookListOK) SetPayload(payload *models.InlineResponse20030) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RelationDefaultBookListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrRelationDefaultBookListDefault error

swagger:response relationDefaultBookListDefault
*/
type NrRelationDefaultBookListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrRelationDefaultBookListDefault creates NrRelationDefaultBookListDefault with default headers values
func NewNrRelationDefaultBookListDefault(code int) *NrRelationDefaultBookListDefault {
	if code <= 0 {
		code = 500
	}

	return &NrRelationDefaultBookListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the relation default book list default response
func (o *NrRelationDefaultBookListDefault) WithStatusCode(code int) *NrRelationDefaultBookListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the relation default book list default response
func (o *NrRelationDefaultBookListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the relation default book list default response
func (o *NrRelationDefaultBookListDefault) WithPayload(payload *models.Error) *NrRelationDefaultBookListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation default book list default response
func (o *NrRelationDefaultBookListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrRelationDefaultBookListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
