// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/tingtingbackend/models"
)

// RelationSubCategoryAlbumListEditOKCode is the HTTP code returned for type RelationSubCategoryAlbumListEditOK
const RelationSubCategoryAlbumListEditOKCode int = 200

/*RelationSubCategoryAlbumListEditOK 操作成功，返回操作信息

swagger:response relationSubCategoryAlbumListEditOK
*/
type RelationSubCategoryAlbumListEditOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20017 `json:"body,omitempty"`
}

// NewRelationSubCategoryAlbumListEditOK creates RelationSubCategoryAlbumListEditOK with default headers values
func NewRelationSubCategoryAlbumListEditOK() *RelationSubCategoryAlbumListEditOK {
	return &RelationSubCategoryAlbumListEditOK{}
}

// WithPayload adds the payload to the relation sub category album list edit o k response
func (o *RelationSubCategoryAlbumListEditOK) WithPayload(payload *models.InlineResponse20017) *RelationSubCategoryAlbumListEditOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation sub category album list edit o k response
func (o *RelationSubCategoryAlbumListEditOK) SetPayload(payload *models.InlineResponse20017) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RelationSubCategoryAlbumListEditOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrRelationSubCategoryAlbumListEditDefault error

swagger:response relationSubCategoryAlbumListEditDefault
*/
type NrRelationSubCategoryAlbumListEditDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrRelationSubCategoryAlbumListEditDefault creates NrRelationSubCategoryAlbumListEditDefault with default headers values
func NewNrRelationSubCategoryAlbumListEditDefault(code int) *NrRelationSubCategoryAlbumListEditDefault {
	if code <= 0 {
		code = 500
	}

	return &NrRelationSubCategoryAlbumListEditDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the relation sub category album list edit default response
func (o *NrRelationSubCategoryAlbumListEditDefault) WithStatusCode(code int) *NrRelationSubCategoryAlbumListEditDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the relation sub category album list edit default response
func (o *NrRelationSubCategoryAlbumListEditDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the relation sub category album list edit default response
func (o *NrRelationSubCategoryAlbumListEditDefault) WithPayload(payload *models.Error) *NrRelationSubCategoryAlbumListEditDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation sub category album list edit default response
func (o *NrRelationSubCategoryAlbumListEditDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrRelationSubCategoryAlbumListEditDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
