// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrRelationSubCategoryAlbumListEditHandlerFunc turns a function with the right signature into a relation sub category album list edit handler
type NrRelationSubCategoryAlbumListEditHandlerFunc func(NrRelationSubCategoryAlbumListEditParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrRelationSubCategoryAlbumListEditHandlerFunc) Handle(params NrRelationSubCategoryAlbumListEditParams) middleware.Responder {
	return fn(params)
}

// NrRelationSubCategoryAlbumListEditHandler interface for that can handle valid relation sub category album list edit params
type NrRelationSubCategoryAlbumListEditHandler interface {
	Handle(NrRelationSubCategoryAlbumListEditParams) middleware.Responder
}

// NewNrRelationSubCategoryAlbumListEdit creates a new http.Handler for the relation sub category album list edit operation
func NewNrRelationSubCategoryAlbumListEdit(ctx *middleware.Context, handler NrRelationSubCategoryAlbumListEditHandler) *NrRelationSubCategoryAlbumListEdit {
	return &NrRelationSubCategoryAlbumListEdit{Context: ctx, Handler: handler}
}

/*NrRelationSubCategoryAlbumListEdit swagger:route POST /relation/subCategory/albumList/edit Relation relationSubCategoryAlbumListEdit

编辑子类下的专辑集合

编辑子类下的专辑集合

*/
type NrRelationSubCategoryAlbumListEdit struct {
	Context *middleware.Context
	Handler NrRelationSubCategoryAlbumListEditHandler
}

func (o *NrRelationSubCategoryAlbumListEdit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrRelationSubCategoryAlbumListEditParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
