// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/tingtingbackend/models"
)

// RelationAlbumBooklistEditOKCode is the HTTP code returned for type RelationAlbumBooklistEditOK
const RelationAlbumBooklistEditOKCode int = 200

/*RelationAlbumBooklistEditOK 操作成功，返回操作信息

swagger:response relationAlbumBooklistEditOK
*/
type RelationAlbumBooklistEditOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20017 `json:"body,omitempty"`
}

// NewRelationAlbumBooklistEditOK creates RelationAlbumBooklistEditOK with default headers values
func NewRelationAlbumBooklistEditOK() *RelationAlbumBooklistEditOK {
	return &RelationAlbumBooklistEditOK{}
}

// WithPayload adds the payload to the relation album booklist edit o k response
func (o *RelationAlbumBooklistEditOK) WithPayload(payload *models.InlineResponse20017) *RelationAlbumBooklistEditOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation album booklist edit o k response
func (o *RelationAlbumBooklistEditOK) SetPayload(payload *models.InlineResponse20017) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RelationAlbumBooklistEditOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrRelationAlbumBooklistEditDefault error

swagger:response relationAlbumBooklistEditDefault
*/
type NrRelationAlbumBooklistEditDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrRelationAlbumBooklistEditDefault creates NrRelationAlbumBooklistEditDefault with default headers values
func NewNrRelationAlbumBooklistEditDefault(code int) *NrRelationAlbumBooklistEditDefault {
	if code <= 0 {
		code = 500
	}

	return &NrRelationAlbumBooklistEditDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the relation album booklist edit default response
func (o *NrRelationAlbumBooklistEditDefault) WithStatusCode(code int) *NrRelationAlbumBooklistEditDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the relation album booklist edit default response
func (o *NrRelationAlbumBooklistEditDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the relation album booklist edit default response
func (o *NrRelationAlbumBooklistEditDefault) WithPayload(payload *models.Error) *NrRelationAlbumBooklistEditDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation album booklist edit default response
func (o *NrRelationAlbumBooklistEditDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrRelationAlbumBooklistEditDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
