// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackend/models"
)

// RelationSubCategoryBannerListEditOKCode is the HTTP code returned for type RelationSubCategoryBannerListEditOK
const RelationSubCategoryBannerListEditOKCode int = 200

/*RelationSubCategoryBannerListEditOK 操作成功，返回操作信息

swagger:response relationSubCategoryBannerListEditOK
*/
type RelationSubCategoryBannerListEditOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2003 `json:"body,omitempty"`
}

// NewRelationSubCategoryBannerListEditOK creates RelationSubCategoryBannerListEditOK with default headers values
func NewRelationSubCategoryBannerListEditOK() *RelationSubCategoryBannerListEditOK {
	return &RelationSubCategoryBannerListEditOK{}
}

// WithPayload adds the payload to the relation sub category banner list edit o k response
func (o *RelationSubCategoryBannerListEditOK) WithPayload(payload *models.InlineResponse2003) *RelationSubCategoryBannerListEditOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation sub category banner list edit o k response
func (o *RelationSubCategoryBannerListEditOK) SetPayload(payload *models.InlineResponse2003) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RelationSubCategoryBannerListEditOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrRelationSubCategoryBannerListEditDefault error

swagger:response relationSubCategoryBannerListEditDefault
*/
type NrRelationSubCategoryBannerListEditDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrRelationSubCategoryBannerListEditDefault creates NrRelationSubCategoryBannerListEditDefault with default headers values
func NewNrRelationSubCategoryBannerListEditDefault(code int) *NrRelationSubCategoryBannerListEditDefault {
	if code <= 0 {
		code = 500
	}

	return &NrRelationSubCategoryBannerListEditDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the relation sub category banner list edit default response
func (o *NrRelationSubCategoryBannerListEditDefault) WithStatusCode(code int) *NrRelationSubCategoryBannerListEditDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the relation sub category banner list edit default response
func (o *NrRelationSubCategoryBannerListEditDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the relation sub category banner list edit default response
func (o *NrRelationSubCategoryBannerListEditDefault) WithPayload(payload *models.Error) *NrRelationSubCategoryBannerListEditDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation sub category banner list edit default response
func (o *NrRelationSubCategoryBannerListEditDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrRelationSubCategoryBannerListEditDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
