// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackend/models"
)

// RelationCategorySubCategoryListEditOKCode is the HTTP code returned for type RelationCategorySubCategoryListEditOK
const RelationCategorySubCategoryListEditOKCode int = 200

/*RelationCategorySubCategoryListEditOK 操作成功，返回操作信息

swagger:response relationCategorySubCategoryListEditOK
*/
type RelationCategorySubCategoryListEditOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20018 `json:"body,omitempty"`
}

// NewRelationCategorySubCategoryListEditOK creates RelationCategorySubCategoryListEditOK with default headers values
func NewRelationCategorySubCategoryListEditOK() *RelationCategorySubCategoryListEditOK {
	return &RelationCategorySubCategoryListEditOK{}
}

// WithPayload adds the payload to the relation category sub category list edit o k response
func (o *RelationCategorySubCategoryListEditOK) WithPayload(payload *models.InlineResponse20018) *RelationCategorySubCategoryListEditOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation category sub category list edit o k response
func (o *RelationCategorySubCategoryListEditOK) SetPayload(payload *models.InlineResponse20018) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RelationCategorySubCategoryListEditOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrRelationCategorySubCategoryListEditDefault error

swagger:response relationCategorySubCategoryListEditDefault
*/
type NrRelationCategorySubCategoryListEditDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrRelationCategorySubCategoryListEditDefault creates NrRelationCategorySubCategoryListEditDefault with default headers values
func NewNrRelationCategorySubCategoryListEditDefault(code int) *NrRelationCategorySubCategoryListEditDefault {
	if code <= 0 {
		code = 500
	}

	return &NrRelationCategorySubCategoryListEditDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the relation category sub category list edit default response
func (o *NrRelationCategorySubCategoryListEditDefault) WithStatusCode(code int) *NrRelationCategorySubCategoryListEditDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the relation category sub category list edit default response
func (o *NrRelationCategorySubCategoryListEditDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the relation category sub category list edit default response
func (o *NrRelationCategorySubCategoryListEditDefault) WithPayload(payload *models.Error) *NrRelationCategorySubCategoryListEditDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation category sub category list edit default response
func (o *NrRelationCategorySubCategoryListEditDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrRelationCategorySubCategoryListEditDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
