// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackend/models"
)

// RelationDefaultBookUploadOKCode is the HTTP code returned for type RelationDefaultBookUploadOK
const RelationDefaultBookUploadOKCode int = 200

/*RelationDefaultBookUploadOK 操作成功，返回操作信息

swagger:response relationDefaultBookUploadOK
*/
type RelationDefaultBookUploadOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2003 `json:"body,omitempty"`
}

// NewRelationDefaultBookUploadOK creates RelationDefaultBookUploadOK with default headers values
func NewRelationDefaultBookUploadOK() *RelationDefaultBookUploadOK {
	return &RelationDefaultBookUploadOK{}
}

// WithPayload adds the payload to the relation default book upload o k response
func (o *RelationDefaultBookUploadOK) WithPayload(payload *models.InlineResponse2003) *RelationDefaultBookUploadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation default book upload o k response
func (o *RelationDefaultBookUploadOK) SetPayload(payload *models.InlineResponse2003) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RelationDefaultBookUploadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrRelationDefaultBookUploadDefault error

swagger:response relationDefaultBookUploadDefault
*/
type NrRelationDefaultBookUploadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrRelationDefaultBookUploadDefault creates NrRelationDefaultBookUploadDefault with default headers values
func NewNrRelationDefaultBookUploadDefault(code int) *NrRelationDefaultBookUploadDefault {
	if code <= 0 {
		code = 500
	}

	return &NrRelationDefaultBookUploadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the relation default book upload default response
func (o *NrRelationDefaultBookUploadDefault) WithStatusCode(code int) *NrRelationDefaultBookUploadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the relation default book upload default response
func (o *NrRelationDefaultBookUploadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the relation default book upload default response
func (o *NrRelationDefaultBookUploadDefault) WithPayload(payload *models.Error) *NrRelationDefaultBookUploadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the relation default book upload default response
func (o *NrRelationDefaultBookUploadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrRelationDefaultBookUploadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
