// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/tingtingbackend/models"
)

// NewNrRelationCategorySubCategoryListEditParams creates a new NrRelationCategorySubCategoryListEditParams object
// with the default values initialized.
func NewNrRelationCategorySubCategoryListEditParams() NrRelationCategorySubCategoryListEditParams {
	var ()
	return NrRelationCategorySubCategoryListEditParams{}
}

// NrRelationCategorySubCategoryListEditParams contains all the bound params for the relation category sub category list edit operation
// typically these are obtained from a http.Request
//
// swagger:parameters /relation/Category/subCategoryList/edit
type NrRelationCategorySubCategoryListEditParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*编辑大类下的子类集合
	  In: body
	*/
	Body *models.Body3
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *NrRelationCategorySubCategoryListEditParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Body3
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
