// Code generated by go-swagger; DO NOT EDIT.

package relation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrRelationSubCategoryIconrListEditHandlerFunc turns a function with the right signature into a relation sub category iconr list edit handler
type NrRelationSubCategoryIconrListEditHandlerFunc func(NrRelationSubCategoryIconrListEditParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrRelationSubCategoryIconrListEditHandlerFunc) Handle(params NrRelationSubCategoryIconrListEditParams) middleware.Responder {
	return fn(params)
}

// NrRelationSubCategoryIconrListEditHandler interface for that can handle valid relation sub category iconr list edit params
type NrRelationSubCategoryIconrListEditHandler interface {
	Handle(NrRelationSubCategoryIconrListEditParams) middleware.Responder
}

// NewNrRelationSubCategoryIconrListEdit creates a new http.Handler for the relation sub category iconr list edit operation
func NewNrRelationSubCategoryIconrListEdit(ctx *middleware.Context, handler NrRelationSubCategoryIconrListEditHandler) *NrRelationSubCategoryIconrListEdit {
	return &NrRelationSubCategoryIconrListEdit{Context: ctx, Handler: handler}
}

/*NrRelationSubCategoryIconrListEdit swagger:route POST /relation/subCategory/iconList/edit Relation relationSubCategoryIconrListEdit

编辑子类下的icon集合

编辑子类下的icon集合

*/
type NrRelationSubCategoryIconrListEdit struct {
	Context *middleware.Context
	Handler NrRelationSubCategoryIconrListEditHandler
}

func (o *NrRelationSubCategoryIconrListEdit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrRelationSubCategoryIconrListEditParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
