// Code generated by go-swagger; DO NOT EDIT.

package chapter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/tingtingbackend/models"
)

// ChapterDeleteOKCode is the HTTP code returned for type ChapterDeleteOK
const ChapterDeleteOKCode int = 200

/*ChapterDeleteOK 章节详情

swagger:response chapterDeleteOK
*/
type ChapterDeleteOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20017 `json:"body,omitempty"`
}

// NewChapterDeleteOK creates ChapterDeleteOK with default headers values
func NewChapterDeleteOK() *ChapterDeleteOK {
	return &ChapterDeleteOK{}
}

// WithPayload adds the payload to the chapter delete o k response
func (o *ChapterDeleteOK) WithPayload(payload *models.InlineResponse20017) *ChapterDeleteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chapter delete o k response
func (o *ChapterDeleteOK) SetPayload(payload *models.InlineResponse20017) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChapterDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ChapterDeleteDefault error

swagger:response chapterDeleteDefault
*/
type ChapterDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewChapterDeleteDefault creates ChapterDeleteDefault with default headers values
func NewChapterDeleteDefault(code int) *ChapterDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &ChapterDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the chapter delete default response
func (o *ChapterDeleteDefault) WithStatusCode(code int) *ChapterDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the chapter delete default response
func (o *ChapterDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the chapter delete default response
func (o *ChapterDeleteDefault) WithPayload(payload *models.Error) *ChapterDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chapter delete default response
func (o *ChapterDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChapterDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
