// Code generated by go-swagger; DO NOT EDIT.

package chapter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackend/models"
)

// ChapterHistoryListOKCode is the HTTP code returned for type ChapterHistoryListOK
const ChapterHistoryListOKCode int = 200

/*ChapterHistoryListOK 登录成功，返回登录信息

swagger:response chapterHistoryListOK
*/
type ChapterHistoryListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20023 `json:"body,omitempty"`
}

// NewChapterHistoryListOK creates ChapterHistoryListOK with default headers values
func NewChapterHistoryListOK() *ChapterHistoryListOK {
	return &ChapterHistoryListOK{}
}

// WithPayload adds the payload to the chapter history list o k response
func (o *ChapterHistoryListOK) WithPayload(payload *models.InlineResponse20023) *ChapterHistoryListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chapter history list o k response
func (o *ChapterHistoryListOK) SetPayload(payload *models.InlineResponse20023) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChapterHistoryListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ChapterHistoryListDefault error

swagger:response chapterHistoryListDefault
*/
type ChapterHistoryListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewChapterHistoryListDefault creates ChapterHistoryListDefault with default headers values
func NewChapterHistoryListDefault(code int) *ChapterHistoryListDefault {
	if code <= 0 {
		code = 500
	}

	return &ChapterHistoryListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the chapter history list default response
func (o *ChapterHistoryListDefault) WithStatusCode(code int) *ChapterHistoryListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the chapter history list default response
func (o *ChapterHistoryListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the chapter history list default response
func (o *ChapterHistoryListDefault) WithPayload(payload *models.Error) *ChapterHistoryListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chapter history list default response
func (o *ChapterHistoryListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChapterHistoryListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
