// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TagEditHandlerFunc turns a function with the right signature into a tag edit handler
type TagEditHandlerFunc func(TagEditParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TagEditHandlerFunc) Handle(params TagEditParams) middleware.Responder {
	return fn(params)
}

// TagEditHandler interface for that can handle valid tag edit params
type TagEditHandler interface {
	Handle(TagEditParams) middleware.Responder
}

// NewTagEdit creates a new http.Handler for the tag edit operation
func NewTagEdit(ctx *middleware.Context, handler TagEditHandler) *TagEdit {
	return &TagEdit{Context: ctx, Handler: handler}
}

/*TagEdit swagger:route POST /tag/edit Tag tagEdit

编辑一个专辑

*/
type TagEdit struct {
	Context *middleware.Context
	Handler TagEditHandler
}

func (o *TagEdit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTagEditParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
