// Code generated by go-swagger; DO NOT EDIT.

package banner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackend/models"
)

// BannerDeleteOKCode is the HTTP code returned for type BannerDeleteOK
const BannerDeleteOKCode int = 200

/*BannerDeleteOK 详情

swagger:response bannerDeleteOK
*/
type BannerDeleteOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2003 `json:"body,omitempty"`
}

// NewBannerDeleteOK creates BannerDeleteOK with default headers values
func NewBannerDeleteOK() *BannerDeleteOK {
	return &BannerDeleteOK{}
}

// WithPayload adds the payload to the banner delete o k response
func (o *BannerDeleteOK) WithPayload(payload *models.InlineResponse2003) *BannerDeleteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the banner delete o k response
func (o *BannerDeleteOK) SetPayload(payload *models.InlineResponse2003) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BannerDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BannerDeleteDefault error

swagger:response bannerDeleteDefault
*/
type BannerDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBannerDeleteDefault creates BannerDeleteDefault with default headers values
func NewBannerDeleteDefault(code int) *BannerDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &BannerDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the banner delete default response
func (o *BannerDeleteDefault) WithStatusCode(code int) *BannerDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the banner delete default response
func (o *BannerDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the banner delete default response
func (o *BannerDeleteDefault) WithPayload(payload *models.Error) *BannerDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the banner delete default response
func (o *BannerDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BannerDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
