// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrUserDeleteHandlerFunc turns a function with the right signature into a user delete handler
type NrUserDeleteHandlerFunc func(NrUserDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrUserDeleteHandlerFunc) Handle(params NrUserDeleteParams) middleware.Responder {
	return fn(params)
}

// NrUserDeleteHandler interface for that can handle valid user delete params
type NrUserDeleteHandler interface {
	Handle(NrUserDeleteParams) middleware.Responder
}

// NewNrUserDelete creates a new http.Handler for the user delete operation
func NewNrUserDelete(ctx *middleware.Context, handler NrUserDeleteHandler) *NrUserDelete {
	return &NrUserDelete{Context: ctx, Handler: handler}
}

/*NrUserDelete swagger:route GET /user/delete User userDelete

删除用户接口

删除用户接口

*/
type NrUserDelete struct {
	Context *middleware.Context
	Handler NrUserDeleteHandler
}

func (o *NrUserDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrUserDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
