// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrUserListHandlerFunc turns a function with the right signature into a user list handler
type NrUserListHandlerFunc func(NrUserListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrUserListHandlerFunc) Handle(params NrUserListParams) middleware.Responder {
	return fn(params)
}

// NrUserListHandler interface for that can handle valid user list params
type NrUserListHandler interface {
	Handle(NrUserListParams) middleware.Responder
}

// NewNrUserList creates a new http.Handler for the user list operation
func NewNrUserList(ctx *middleware.Context, handler NrUserListHandler) *NrUserList {
	return &NrUserList{Context: ctx, Handler: handler}
}

/*NrUserList swagger:route GET /user/list User userList

获取后台用户列表

获取后台用户列表

*/
type NrUserList struct {
	Context *middleware.Context
	Handler NrUserListHandler
}

func (o *NrUserList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrUserListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
