// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/tingtingbackend/models"
)

// SearchOKCode is the HTTP code returned for type SearchOK
const SearchOKCode int = 200

/*SearchOK 搜索结果

swagger:response searchOK
*/
type SearchOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2008 `json:"body,omitempty"`
}

// NewSearchOK creates SearchOK with default headers values
func NewSearchOK() *SearchOK {
	return &SearchOK{}
}

// WithPayload adds the payload to the search o k response
func (o *SearchOK) WithPayload(payload *models.InlineResponse2008) *SearchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search o k response
func (o *SearchOK) SetPayload(payload *models.InlineResponse2008) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*SearchDefault error

swagger:response searchDefault
*/
type SearchDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewSearchDefault creates SearchDefault with default headers values
func NewSearchDefault(code int) *SearchDefault {
	if code <= 0 {
		code = 500
	}

	return &SearchDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the search default response
func (o *SearchDefault) WithStatusCode(code int) *SearchDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the search default response
func (o *SearchDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the search default response
func (o *SearchDefault) WithPayload(payload *models.Error) *SearchDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the search default response
func (o *SearchDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *SearchDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
