// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BookUploadHandlerFunc turns a function with the right signature into a book upload handler
type BookUploadHandlerFunc func(BookUploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BookUploadHandlerFunc) Handle(params BookUploadParams) middleware.Responder {
	return fn(params)
}

// BookUploadHandler interface for that can handle valid book upload params
type BookUploadHandler interface {
	Handle(BookUploadParams) middleware.Responder
}

// NewBookUpload creates a new http.Handler for the book upload operation
func NewBookUpload(ctx *middleware.Context, handler BookUploadHandler) *BookUpload {
	return &BookUpload{Context: ctx, Handler: handler}
}

/*BookUpload swagger:route POST /book/upload Book bookUpload

添加一本书

*/
type BookUpload struct {
	Context *middleware.Context
	Handler BookUploadHandler
}

func (o *BookUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBookUploadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
