// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackend/models"
)

// BookDetailOKCode is the HTTP code returned for type BookDetailOK
const BookDetailOKCode int = 200

/*BookDetailOK 书本详情

swagger:response bookDetailOK
*/
type BookDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20022 `json:"body,omitempty"`
}

// NewBookDetailOK creates BookDetailOK with default headers values
func NewBookDetailOK() *BookDetailOK {
	return &BookDetailOK{}
}

// WithPayload adds the payload to the book detail o k response
func (o *BookDetailOK) WithPayload(payload *models.InlineResponse20022) *BookDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book detail o k response
func (o *BookDetailOK) SetPayload(payload *models.InlineResponse20022) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BookDetailDefault error

swagger:response bookDetailDefault
*/
type BookDetailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBookDetailDefault creates BookDetailDefault with default headers values
func NewBookDetailDefault(code int) *BookDetailDefault {
	if code <= 0 {
		code = 500
	}

	return &BookDetailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the book detail default response
func (o *BookDetailDefault) WithStatusCode(code int) *BookDetailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the book detail default response
func (o *BookDetailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the book detail default response
func (o *BookDetailDefault) WithPayload(payload *models.Error) *BookDetailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book detail default response
func (o *BookDetailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookDetailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
