// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	_"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	middleware "github.com/go-openapi/runtime/middleware"
	"tingtingbackend/models"
	"fmt"
	"tingtingbackend/var"
	"strconv"
)

// BookDeleteHandlerFunc turns a function with the right signature into a book delete handler
type BookDeleteHandlerFunc func(BookDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BookDeleteHandlerFunc) Handle(params BookDeleteParams) middleware.Responder {
	return fn(params)
}

// BookDeleteHandler interface for that can handle valid book delete params
type BookDeleteHandler interface {
	Handle(BookDeleteParams) middleware.Responder
}

// NewBookDelete creates a new http.Handler for the book delete operation
func NewBookDelete(ctx *middleware.Context, handler BookDeleteHandler) *BookDelete {
	return &BookDelete{Context: ctx, Handler: handler}
}

/*BookDelete swagger:route GET /book/delete Book bookDelete

删除书本

删除书本

*/
type BookDelete struct {
	Context *middleware.Context
	Handler BookDeleteHandler
}

func (o *BookDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBookDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	var ok BookDeleteOK
	var response models.InlineResponse20018

	db,err := _var.OpenConnection()
	if err!=nil{
		fmt.Println(err.Error())
	}

	fmt.Println("iconid is",*(Params.BookID))
	var bid int64
	bid,er := strconv.ParseInt(*(Params.BookID), 10, 64)
	if er !=nil{

	}
	//判断是删除book还是删除defaultbook
	if(Params.Action !=nil){
		db.Exec("update book_default_grade_relation set status=1 where id=?",bid)
	}else{
		db.Exec("update books set status=1 where id=?",bid)
	}

	//status
	var status models.Response
	status.UnmarshalBinary([]byte(_var.Response200(200,"ok")))
	response.Status = &status

	ok.SetPayload(&response)

	o.Context.Respond(rw, r, route.Produces, route, ok)

}
