// Code generated by go-swagger; DO NOT EDIT.

package app_ver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AppVersionEditHandlerFunc turns a function with the right signature into a app version edit handler
type AppVersionEditHandlerFunc func(AppVersionEditParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AppVersionEditHandlerFunc) Handle(params AppVersionEditParams) middleware.Responder {
	return fn(params)
}

// AppVersionEditHandler interface for that can handle valid app version edit params
type AppVersionEditHandler interface {
	Handle(AppVersionEditParams) middleware.Responder
}

// NewAppVersionEdit creates a new http.Handler for the app version edit operation
func NewAppVersionEdit(ctx *middleware.Context, handler AppVersionEditHandler) *AppVersionEdit {
	return &AppVersionEdit{Context: ctx, Handler: handler}
}

/*AppVersionEdit swagger:route POST /appVersion/edit AppVer appVersionEdit

编辑

*/
type AppVersionEdit struct {
	Context *middleware.Context
	Handler AppVersionEditHandler
}

func (o *AppVersionEdit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAppVersionEditParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
