// Code generated by go-swagger; DO NOT EDIT.

package app_ver

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAppVersionEditParams creates a new AppVersionEditParams object
// with the default values initialized.
func NewAppVersionEditParams() AppVersionEditParams {
	var ()
	return AppVersionEditParams{}
}

// AppVersionEditParams contains all the bound params for the app version edit operation
// typically these are obtained from a http.Request
//
// swagger:parameters appVersion/edit/
type AppVersionEditParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: formData
	*/
	Client *string
	/*
	  In: formData
	*/
	DownloadURL *string
	/*
	  In: formData
	*/
	Force *float64
	/*
	  In: formData
	*/
	ID *int64
	/*
	  In: formData
	*/
	Msg *string
	/*
	  In: formData
	*/
	Number *float64
	/*
	  In: formData
	*/
	Status *int64

	Cover *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *AppVersionEditParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if err := r.ParseMultipartForm(32 << 20); err != nil {
		if err != http.ErrNotMultipart {
			return err
		} else if err := r.ParseForm(); err != nil {
			return err
		}
	}
	fds := runtime.Values(r.Form)

	fdClient, fdhkClient, _ := fds.GetOK("client")
	if err := o.bindClient(fdClient, fdhkClient, route.Formats); err != nil {
		res = append(res, err)
	}

	fdDownloadURL, fdhkDownloadURL, _ := fds.GetOK("downloadUrl")
	if err := o.bindDownloadURL(fdDownloadURL, fdhkDownloadURL, route.Formats); err != nil {
		res = append(res, err)
	}

	fdForce, fdhkForce, _ := fds.GetOK("force")
	if err := o.bindForce(fdForce, fdhkForce, route.Formats); err != nil {
		res = append(res, err)
	}

	fdID, fdhkID, _ := fds.GetOK("id")
	if err := o.bindID(fdID, fdhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	fdMsg, fdhkMsg, _ := fds.GetOK("msg")
	if err := o.bindMsg(fdMsg, fdhkMsg, route.Formats); err != nil {
		res = append(res, err)
	}

	fdCover, fdhkCover, _ := fds.GetOK("cover")
	if err := o.bindCover(fdCover, fdhkCover, route.Formats); err != nil {
		res = append(res, err)
	}

	fdNumber, fdhkNumber, _ := fds.GetOK("number")
	if err := o.bindNumber(fdNumber, fdhkNumber, route.Formats); err != nil {
		res = append(res, err)
	}

	fdStatus, fdhkStatus, _ := fds.GetOK("status")
	if err := o.bindStatus(fdStatus, fdhkStatus, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AppVersionEditParams) bindClient(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Client = &raw

	return nil
}

func (o *AppVersionEditParams) bindDownloadURL(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.DownloadURL = &raw

	return nil
}

func (o *AppVersionEditParams) bindForce(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertFloat64(raw)
	if err != nil {
		return errors.InvalidType("force", "formData", "float64", raw)
	}
	o.Force = &value

	return nil
}

func (o *AppVersionEditParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("id", "formData", "int64", raw)
	}
	o.ID = &value

	return nil
}

func (o *AppVersionEditParams) bindCover(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Cover = &raw

	return nil
}

func (o *AppVersionEditParams) bindMsg(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Msg = &raw

	return nil
}

func (o *AppVersionEditParams) bindNumber(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertFloat64(raw)
	if err != nil {
		return errors.InvalidType("number", "formData", "float64", raw)
	}
	o.Number = &value

	return nil
}

func (o *AppVersionEditParams) bindStatus(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("status", "formData", "int64", raw)
	}
	o.Status = &value

	return nil
}
