// Code generated by go-swagger; DO NOT EDIT.

package icon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackend/models"
)

// IconDeleteOKCode is the HTTP code returned for type IconDeleteOK
const IconDeleteOKCode int = 200

/*IconDeleteOK 详情

swagger:response iconDeleteOK
*/
type IconDeleteOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2003 `json:"body,omitempty"`
}

// NewIconDeleteOK creates IconDeleteOK with default headers values
func NewIconDeleteOK() *IconDeleteOK {
	return &IconDeleteOK{}
}

// WithPayload adds the payload to the icon delete o k response
func (o *IconDeleteOK) WithPayload(payload *models.InlineResponse2003) *IconDeleteOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the icon delete o k response
func (o *IconDeleteOK) SetPayload(payload *models.InlineResponse2003) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IconDeleteOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*IconDeleteDefault error

swagger:response iconDeleteDefault
*/
type IconDeleteDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewIconDeleteDefault creates IconDeleteDefault with default headers values
func NewIconDeleteDefault(code int) *IconDeleteDefault {
	if code <= 0 {
		code = 500
	}

	return &IconDeleteDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the icon delete default response
func (o *IconDeleteDefault) WithStatusCode(code int) *IconDeleteDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the icon delete default response
func (o *IconDeleteDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the icon delete default response
func (o *IconDeleteDefault) WithPayload(payload *models.Error) *IconDeleteDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the icon delete default response
func (o *IconDeleteDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IconDeleteDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
