// Code generated by go-swagger; DO NOT EDIT.

package icon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	_"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	middleware "github.com/go-openapi/runtime/middleware"
	"tingtingbackend/models"
	"fmt"
	"tingtingbackend/var"
)

// IconDetailHandlerFunc turns a function with the right signature into a icon detail handler
type IconDetailHandlerFunc func(IconDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn IconDetailHandlerFunc) Handle(params IconDetailParams) middleware.Responder {
	return fn(params)
}

// IconDetailHandler interface for that can handle valid icon detail params
type IconDetailHandler interface {
	Handle(IconDetailParams) middleware.Responder
}

// NewIconDetail creates a new http.Handler for the icon detail operation
func NewIconDetail(ctx *middleware.Context, handler IconDetailHandler) *IconDetail {
	return &IconDetail{Context: ctx, Handler: handler}
}

/*IconDetail swagger:route GET /icon/detail Icon iconDetail

r详情

详情

*/
type IconDetail struct {
	Context *middleware.Context
	Handler IconDetailHandler
}

func (o *IconDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewIconDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	var ok IconDetailOK
	var response models.InlineResponse20010513

	db,err := _var.OpenConnection()
	if err!=nil{
		fmt.Println(err.Error())
	}
	//query
	var icon models.Icon

	db.Table("icons").Where("id=?",Params.IconID).First(&icon)
	//fmt.Println("banner is",banner)
	response.Data = &icon

	//status
	var status models.Response
	status.UnmarshalBinary([]byte(_var.Response200(200,"ok")))
	response.Status = &status

	ok.SetPayload(&response)

	o.Context.Respond(rw, r, route.Produces, route, ok)


}
