// Code generated by go-swagger; DO NOT EDIT.

package album

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AlbumUploadHandlerFunc turns a function with the right signature into a album upload handler
type AlbumUploadHandlerFunc func(AlbumUploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AlbumUploadHandlerFunc) Handle(params AlbumUploadParams) middleware.Responder {
	return fn(params)
}

// AlbumUploadHandler interface for that can handle valid album upload params
type AlbumUploadHandler interface {
	Handle(AlbumUploadParams) middleware.Responder
}

// NewAlbumUpload creates a new http.Handler for the album upload operation
func NewAlbumUpload(ctx *middleware.Context, handler AlbumUploadHandler) *AlbumUpload {
	return &AlbumUpload{Context: ctx, Handler: handler}
}

/*AlbumUpload swagger:route POST /album/upload Album albumUpload

添加一个专辑

*/
type AlbumUpload struct {
	Context *middleware.Context
	Handler AlbumUploadHandler
}

func (o *AlbumUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAlbumUploadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
