// Code generated by go-swagger; DO NOT EDIT.

package jpush

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackend/models"
)

// PushJpushOKCode is the HTTP code returned for type PushJpushOK
const PushJpushOKCode int = 200

/*PushJpushOK 消息详情

swagger:response pushJpushOK
*/
type PushJpushOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20014 `json:"body,omitempty"`
}

// NewPushJpushOK creates PushJpushOK with default headers values
func NewPushJpushOK() *PushJpushOK {
	return &PushJpushOK{}
}

// WithPayload adds the payload to the push jpush o k response
func (o *PushJpushOK) WithPayload(payload *models.InlineResponse20014) *PushJpushOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the push jpush o k response
func (o *PushJpushOK) SetPayload(payload *models.InlineResponse20014) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PushJpushOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PushJpushDefault error

swagger:response pushJpushDefault
*/
type PushJpushDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPushJpushDefault creates PushJpushDefault with default headers values
func NewPushJpushDefault(code int) *PushJpushDefault {
	if code <= 0 {
		code = 500
	}

	return &PushJpushDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the push jpush default response
func (o *PushJpushDefault) WithStatusCode(code int) *PushJpushDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the push jpush default response
func (o *PushJpushDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the push jpush default response
func (o *PushJpushDefault) WithPayload(payload *models.Error) *PushJpushDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the push jpush default response
func (o *PushJpushDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PushJpushDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
