// Code generated by go-swagger; DO NOT EDIT.

package recharge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RechargeListHandlerFunc turns a function with the right signature into a recharge list handler
type RechargeListHandlerFunc func(RechargeListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RechargeListHandlerFunc) Handle(params RechargeListParams) middleware.Responder {
	return fn(params)
}

// RechargeListHandler interface for that can handle valid recharge list params
type RechargeListHandler interface {
	Handle(RechargeListParams) middleware.Responder
}

// NewRechargeList creates a new http.Handler for the recharge list operation
func NewRechargeList(ctx *middleware.Context, handler RechargeListHandler) *RechargeList {
	return &RechargeList{Context: ctx, Handler: handler}
}

/*RechargeList swagger:route POST /recharge/list Recharge rechargeList

获取充值流水列表(含条件检索)

获取订单列表

*/
type RechargeList struct {
	Context *middleware.Context
	Handler RechargeListHandler
}

func (o *RechargeList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRechargeListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
