// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrMemberRecordListHandlerFunc turns a function with the right signature into a member record list handler
type NrMemberRecordListHandlerFunc func(NrMemberRecordListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrMemberRecordListHandlerFunc) Handle(params NrMemberRecordListParams) middleware.Responder {
	return fn(params)
}

// NrMemberRecordListHandler interface for that can handle valid member record list params
type NrMemberRecordListHandler interface {
	Handle(NrMemberRecordListParams) middleware.Responder
}

// NewNrMemberRecordList creates a new http.Handler for the member record list operation
func NewNrMemberRecordList(ctx *middleware.Context, handler NrMemberRecordListHandler) *NrMemberRecordList {
	return &NrMemberRecordList{Context: ctx, Handler: handler}
}

/*NrMemberRecordList swagger:route GET /member/record/list Member memberRecordList

录音列表

录音列表

*/
type NrMemberRecordList struct {
	Context *middleware.Context
	Handler NrMemberRecordListHandler
}

func (o *NrMemberRecordList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrMemberRecordListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
