// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/tingtingbackend/models"
)

// CategoryUploadOKCode is the HTTP code returned for type CategoryUploadOK
const CategoryUploadOKCode int = 200

/*CategoryUploadOK 上传成功，返回成功信息

swagger:response categoryUploadOK
*/
type CategoryUploadOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20015 `json:"body,omitempty"`
}

// NewCategoryUploadOK creates CategoryUploadOK with default headers values
func NewCategoryUploadOK() *CategoryUploadOK {
	return &CategoryUploadOK{}
}

// WithPayload adds the payload to the category upload o k response
func (o *CategoryUploadOK) WithPayload(payload *models.InlineResponse20015) *CategoryUploadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category upload o k response
func (o *CategoryUploadOK) SetPayload(payload *models.InlineResponse20015) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CategoryUploadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CategoryUploadDefault error

swagger:response categoryUploadDefault
*/
type CategoryUploadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCategoryUploadDefault creates CategoryUploadDefault with default headers values
func NewCategoryUploadDefault(code int) *CategoryUploadDefault {
	if code <= 0 {
		code = 500
	}

	return &CategoryUploadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the category upload default response
func (o *CategoryUploadDefault) WithStatusCode(code int) *CategoryUploadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the category upload default response
func (o *CategoryUploadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the category upload default response
func (o *CategoryUploadDefault) WithPayload(payload *models.Error) *CategoryUploadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category upload default response
func (o *CategoryUploadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CategoryUploadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
