// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CategorySubEditHandlerFunc turns a function with the right signature into a category sub edit handler
type CategorySubEditHandlerFunc func(CategorySubEditParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CategorySubEditHandlerFunc) Handle(params CategorySubEditParams) middleware.Responder {
	return fn(params)
}

// CategorySubEditHandler interface for that can handle valid category sub edit params
type CategorySubEditHandler interface {
	Handle(CategorySubEditParams) middleware.Responder
}

// NewCategorySubEdit creates a new http.Handler for the category sub edit operation
func NewCategorySubEdit(ctx *middleware.Context, handler CategorySubEditHandler) *CategorySubEdit {
	return &CategorySubEdit{Context: ctx, Handler: handler}
}

/*CategorySubEdit swagger:route POST /category/sub/edit Category categorySubEdit

编辑一个子类

*/
type CategorySubEdit struct {
	Context *middleware.Context
	Handler CategorySubEditHandler
}

func (o *CategorySubEdit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCategorySubEditParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
