// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CategoryUploadHandlerFunc turns a function with the right signature into a category upload handler
type CategoryUploadHandlerFunc func(CategoryUploadParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CategoryUploadHandlerFunc) Handle(params CategoryUploadParams) middleware.Responder {
	return fn(params)
}

// CategoryUploadHandler interface for that can handle valid category upload params
type CategoryUploadHandler interface {
	Handle(CategoryUploadParams) middleware.Responder
}

// NewCategoryUpload creates a new http.Handler for the category upload operation
func NewCategoryUpload(ctx *middleware.Context, handler CategoryUploadHandler) *CategoryUpload {
	return &CategoryUpload{Context: ctx, Handler: handler}
}

/*CategoryUpload swagger:route POST /category/upload Category categoryUpload

添加一个大类

*/
type CategoryUpload struct {
	Context *middleware.Context
	Handler CategoryUploadHandler
}

func (o *CategoryUpload) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCategoryUploadParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
