// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CategoryEditHandlerFunc turns a function with the right signature into a category edit handler
type CategoryEditHandlerFunc func(CategoryEditParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CategoryEditHandlerFunc) Handle(params CategoryEditParams) middleware.Responder {
	return fn(params)
}

// CategoryEditHandler interface for that can handle valid category edit params
type CategoryEditHandler interface {
	Handle(CategoryEditParams) middleware.Responder
}

// NewCategoryEdit creates a new http.Handler for the category edit operation
func NewCategoryEdit(ctx *middleware.Context, handler CategoryEditHandler) *CategoryEdit {
	return &CategoryEdit{Context: ctx, Handler: handler}
}

/*CategoryEdit swagger:route POST /category/edit Category categoryEdit

编辑大类资料

*/
type CategoryEdit struct {
	Context *middleware.Context
	Handler CategoryEditHandler
}

func (o *CategoryEdit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCategoryEditParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
