// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/tingtingbackend/models"
)

// CategorySubUploadOKCode is the HTTP code returned for type CategorySubUploadOK
const CategorySubUploadOKCode int = 200

/*CategorySubUploadOK 上传成功，返回成功信息

swagger:response categorySubUploadOK
*/
type CategorySubUploadOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20015 `json:"body,omitempty"`
}

// NewCategorySubUploadOK creates CategorySubUploadOK with default headers values
func NewCategorySubUploadOK() *CategorySubUploadOK {
	return &CategorySubUploadOK{}
}

// WithPayload adds the payload to the category sub upload o k response
func (o *CategorySubUploadOK) WithPayload(payload *models.InlineResponse20015) *CategorySubUploadOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category sub upload o k response
func (o *CategorySubUploadOK) SetPayload(payload *models.InlineResponse20015) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CategorySubUploadOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*CategorySubUploadDefault error

swagger:response categorySubUploadDefault
*/
type CategorySubUploadDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCategorySubUploadDefault creates CategorySubUploadDefault with default headers values
func NewCategorySubUploadDefault(code int) *CategorySubUploadDefault {
	if code <= 0 {
		code = 500
	}

	return &CategorySubUploadDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the category sub upload default response
func (o *CategorySubUploadDefault) WithStatusCode(code int) *CategorySubUploadDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the category sub upload default response
func (o *CategorySubUploadDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the category sub upload default response
func (o *CategorySubUploadDefault) WithPayload(payload *models.Error) *CategorySubUploadDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category sub upload default response
func (o *CategorySubUploadDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CategorySubUploadDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
