// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingbackendtest/models"
)

// CategoryBannersEditOKCode is the HTTP code returned for type CategoryBannersEditOK
const CategoryBannersEditOKCode int = 200

/*CategoryBannersEditOK 操作成功，返回操作信息

swagger:response categoryBannersEditOK
*/
type CategoryBannersEditOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2003 `json:"body,omitempty"`
}

// NewCategoryBannersEditOK creates CategoryBannersEditOK with default headers values
func NewCategoryBannersEditOK() *CategoryBannersEditOK {
	return &CategoryBannersEditOK{}
}

// WithPayload adds the payload to the category banners edit o k response
func (o *CategoryBannersEditOK) WithPayload(payload *models.InlineResponse2003) *CategoryBannersEditOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category banners edit o k response
func (o *CategoryBannersEditOK) SetPayload(payload *models.InlineResponse2003) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CategoryBannersEditOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrCategoryBannersEditDefault error

swagger:response categoryBannersEditDefault
*/
type NrCategoryBannersEditDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrCategoryBannersEditDefault creates NrCategoryBannersEditDefault with default headers values
func NewNrCategoryBannersEditDefault(code int) *NrCategoryBannersEditDefault {
	if code <= 0 {
		code = 500
	}

	return &NrCategoryBannersEditDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the category banners edit default response
func (o *NrCategoryBannersEditDefault) WithStatusCode(code int) *NrCategoryBannersEditDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the category banners edit default response
func (o *NrCategoryBannersEditDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the category banners edit default response
func (o *NrCategoryBannersEditDefault) WithPayload(payload *models.Error) *NrCategoryBannersEditDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category banners edit default response
func (o *NrCategoryBannersEditDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrCategoryBannersEditDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
