// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Album album
// swagger:model Album
type Album struct {

	// album Id
	// Required: true
	AlbumID *int64 `json:"albumId"`

	// album name
	// Required: true
	AlbumName *string `json:"albumName"`

	// value
	// Required: true
	Value *float64 `json:"value"`
}

// Validate validates this album
func (m *Album) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAlbumID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateAlbumName(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Album) validateAlbumID(formats strfmt.Registry) error {

	if err := validate.Required("albumId", "body", m.AlbumID); err != nil {
		return err
	}

	return nil
}

func (m *Album) validateAlbumName(formats strfmt.Registry) error {

	if err := validate.Required("albumName", "body", m.AlbumName); err != nil {
		return err
	}

	return nil
}

func (m *Album) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Album) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Album) UnmarshalBinary(b []byte) error {
	var res Album
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
