// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Body7 body 7
// swagger:model body_7
type Body7 struct {

	// 0表示添加，1表示移除
	// Required: true
	ActionCode *int64 `json:"actionCode"`

	// category Id
	// Required: true
	CategoryID *int64 `json:"categoryId"`

	// sub category ids
	// Required: true
	SubCategoryIds *string `json:"subCategoryIds"`
}

// Validate validates this body 7
func (m *Body7) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActionCode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCategoryID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSubCategoryIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Body7) validateActionCode(formats strfmt.Registry) error {

	if err := validate.Required("actionCode", "body", m.ActionCode); err != nil {
		return err
	}

	return nil
}

func (m *Body7) validateCategoryID(formats strfmt.Registry) error {

	if err := validate.Required("categoryId", "body", m.CategoryID); err != nil {
		return err
	}

	return nil
}

func (m *Body7) validateSubCategoryIds(formats strfmt.Registry) error {

	if err := validate.Required("subCategoryIds", "body", m.SubCategoryIds); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Body7) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Body7) UnmarshalBinary(b []byte) error {
	var res Body7
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
