// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Body body
// swagger:model body
type Body struct {
	Id int64 `json:"id,omitempty" gorm:"AUTO_INCREMENT"`
	// 0表示添加，1表示移除
	// Required: true
	ActionCode *int64 `json:"actionCode"`

	// book Id
	// Required: true
	BookID *int64 `json:"bookId"`

	// chapter ids
	// Required: true
	ChapterIds *string `json:"chapterIds"`
}

// Validate validates this body
func (m *Body) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActionCode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateBookID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateChapterIds(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Body) validateActionCode(formats strfmt.Registry) error {

	if err := validate.Required("actionCode", "body", m.ActionCode); err != nil {
		return err
	}

	return nil
}

func (m *Body) validateBookID(formats strfmt.Registry) error {

	if err := validate.Required("bookId", "body", m.BookID); err != nil {
		return err
	}

	return nil
}

func (m *Body) validateChapterIds(formats strfmt.Registry) error {

	if err := validate.Required("chapterIds", "body", m.ChapterIds); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Body) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Body) UnmarshalBinary(b []byte) error {
	var res Body
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
