// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Body5 body 5
// swagger:model body_5
type Body5 struct {

	// 0表示添加，1表示移除
	ActionCode int64 `json:"actionCode,omitempty"`

	// banner ids
	BannerIds string `json:"bannerIds,omitempty"`

	// sub category Id
	SubCategoryID int64 `json:"subCategoryId,omitempty"`
}

// Validate validates this body 5
func (m *Body5) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Body5) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Body5) UnmarshalBinary(b []byte) error {
	var res Body5
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
