// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Book book
// swagger:model Book
type Book struct {

	Id int64 `json:"id,omitempty" gorm:"AUTO_INCREMENT"`

	// author avatar
	AuthorAvatar string `json:"authorAvatar,omitempty"`

	// author name
	AuthorName string `json:"authorName,omitempty"`

	// clips number
	ClipsNumber int64 `json:"clipsNumber,omitempty"`

	// icon
	Icon string `json:"icon,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// play count
	PlayCount int64 `json:"playCount,omitempty"`

	// show icon
	ShowIcon bool `json:"showIcon,omitempty"`

	// status
	Status int64 `json:"status,omitempty"`

	// sub category Id
	SubCategoryID int64 `json:"subCategoryId,omitempty"`

	// sub title
	SubTitle string `json:"subTitle,omitempty"`

	// summary
	Summary string `json:"summary,omitempty"`

	// time
	Time int64 `json:"time,omitempty"`
}

// Validate validates this book
func (m *Book) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Book) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Book) UnmarshalBinary(b []byte) error {
	var res Book
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
