// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InlineResponse200191 inline response 200 19
// swagger:model inline_response_200_19
type InlineResponse200191 struct {

	// return
	Return *Response `json:"return,omitempty"`

	// 上传文件返回的完整路径
	URL string `json:"url,omitempty"`

	OriginName string `json:"originname,omitempty"`
}

// Validate validates this inline response 200 19
func (m *InlineResponse200191) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateReturn(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse200191) validateReturn(formats strfmt.Registry) error {

	if swag.IsZero(m.Return) { // not required
		return nil
	}

	if m.Return != nil {

		if err := m.Return.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("return")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse200191) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse200191) UnmarshalBinary(b []byte) error {
	var res InlineResponse200191
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
